folio-org/mod-erm-usage-counter

mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/Counter5Utils.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/cellprocessor/IdentifierProcessor.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/cellprocessor/MetricTypeProcessor.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/cellprocessor/PerformanceProcessor.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/cellprocessor/PublisherIDProcessor.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/MapperException.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/MapperFactory.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractReportToCsvMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/DR.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/IR.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/PR.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/ReportToCsvMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/TR.java
mod-erm-usage-counter50/src/test/java/org/olf/erm/usage/counter50/csv/mapper/MapperTest.java
mod-erm-usage-counter50/src/test/resources/hwire_trj1.json
mod-erm-usage-counter50/src/test/resources/reports/DR.csv
mod-erm-usage-counter50/src/test/resources/reports/DR.json
mod-erm-usage-counter50/src/test/resources/reports/IR.csv
mod-erm-usage-counter50/src/test/resources/reports/IR.json
mod-erm-usage-counter50/src/test/resources/reports/PR.csv
mod-erm-usage-counter50/src/test/resources/reports/PR.json
mod-erm-usage-counter50/src/test/resources/reports/TR.csv
mod-erm-usage-counter50/src/test/resources/reports/TR.json

Add possibility to download COUNTER 5 reports as csv (for single months).

Uieus 106 download counter5 csv

---

README.md
mod-erm-usage-counter-common/pom.xml
mod-erm-usage-counter41/pom.xml
mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/csv2report/IRCsvToReport.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/IR.java
mod-erm-usage-counter50/src/main/resources/counter-sushi_5_0_api/swagger.yaml
mod-erm-usage-counter50/src/test/resources/reports/IR_1.json
mod-erm-usage-counter50/src/test/resources/reports/IR_2.json
mod-erm-usage-counter50/src/test/resources/reports/IR_merged.json
pom.xml

Update to the latest Counter-Sushi 5.0 API specifcation found [here](https://app.swaggerhub.com/apis/COUNTER/counter-sushi_5_0_api/1.0.0).
Also update the CSV mapper and sample reports to match changes.

MODEUSCNT-9-update-counter-sushi-api-specification

---

mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/dr/DRConverterBase.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/dr/DRD1Converter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/tr/TRB1Converter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/tr/TRB3Converter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/tr/TRConverterBase.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/tr/TRJ1Converter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/tr/TRJ3Converter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/tr/TRJ4Converter.java
mod-erm-usage-counter50/src/test/java/org/olf/erm/usage/counter50/converter/MissingAttributesTest.java

Fix NullPointerExceptions during report conversion

MODEUSCNT-15

---

mod-erm-usage-counter-common/src/main/java/org/olf/erm/usage/counter/common/ExcelUtil.java

Set numeric cell type for numbers in .xlsx

MODEUSCNT-16

---

mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/csv2report/CsvHeaderToReportHeader.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractReportToCsvMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/merger/ReportsMerger.java
mod-erm-usage-counter50/src/test/resources/reports/DR_1.json
mod-erm-usage-counter50/src/test/resources/reports/DR_2.json
mod-erm-usage-counter50/src/test/resources/reports/DR_3.json
mod-erm-usage-counter50/src/test/resources/reports/TRJ1_merged.json

Upgrade `openapi-generator` and `openapi-generator-maven-plugin` to latest version to fix security vulnerabilites CVE-2021-21429, CVE-2021-21430

MODEUSCNT-17

---

NEWS.md
mod-erm-usage-counter-common/pom.xml
mod-erm-usage-counter41/pom.xml
mod-erm-usage-counter50/pom.xml
pom.xml

Merge release branch b2.2 into master

merge-b2.2

---

pom.xml

https://stackoverflow.com/a/4725728

MODEUSCNT-26: Publish javadoc and sources to maven repository

---

pom.xml

Update dependencies with vulnerabilities

MODEUSCNT-35

---

mod-erm-usage-counter-common/src/main/java/org/olf/erm/usage/counter/common/ExcelUtil.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractDRMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractIRMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractPRMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractReportToCsvMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractTRMapper.java

Reduce memory usage when creating csv and xlsx data

MODEUSCNT-37

---

mod-erm-usage-counter-common/pom.xml
mod-erm-usage-counter41/pom.xml
mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/Counter5Utils.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/converter/ReportConverter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/csv2report/CsvHeaderToReportHeader.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/csv/mapper/report2csv/AbstractReportToCsvMapper.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/splitter/DRReportsSplitter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/splitter/IRReportsSplitter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/splitter/PRReportsSplitter.java
mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/splitter/TRReportsSplitter.java
mod-erm-usage-counter50/src/main/resources/counter-sushi_5_0_api/counter5.0.2.yaml
pom.xml

Switch to vertx generator library

MODEUSCNT-8

---

mod-erm-usage-counter50/src/main/java/org/olf/erm/usage/counter50/merger/ReportsMerger.java
mod-erm-usage-counter50/src/test/java/org/olf/erm/usage/counter50/merger/ReportsMergerTest.java

Add null checks to ReportsMerger::mergeHeaders

MODEUSCNT-41

---

NEWS.md
mod-erm-usage-counter-common/pom.xml
mod-erm-usage-counter41/pom.xml
mod-erm-usage-counter50/pom.xml
pom.xml

MODEUSCNT-42

---

mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter50/src/main/resources/counter-sushi_5_0_api/COUNTER-counter-sushi_5_0_api-5.0.3-swagger.yaml
mod-erm-usage-counter50/src/test/java/org/olf/erm/usage/counter50/Counter5UtilsTest.java
mod-erm-usage-counter50/src/test/resources/wiley_tr.json

Update counter openapi specification

MODEUSCNT-45

---

mod-erm-usage-counter51/pom.xml
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/Counter51Utils.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/JsonProperties.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ObjectMapperFactory.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportMerger.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportSplitter.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ValidationBeanDeserializerModifier.java
mod-erm-usage-counter51/src/test/java/org/olf/erm/usage/counter51/Counter51UtilsTest.java
mod-erm-usage-counter51/src/test/java/org/olf/erm/usage/counter51/ObjectMapperTest.java

https://folio-org.atlassian.net/browse/MODEUSCNT-49
Add utility methods to split/merge COUNTER 5.1 reports

MODEUSCNT-49 Add utility methods to split/merge COUNTER 5.1 reports

---

CONTRIBUTING.md
pom.xml

* Adds `spotless-maven-plugin` and `CONTRIBUTING.md` with usage information.

Add `spotless-maven-plugin` and add `CONTRIBUTING.md`

---

mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportSplitter.java
mod-erm-usage-counter51/src/test/java/org/olf/erm/usage/counter51/Counter51UtilsTest.java

https://folio-org.atlassian.net/browse/MODEUSCNT-53
* Fixes splitting of IR reports

[MODEUSCNT-53] Fix splitting of IR reports

---

mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/Counter51Utils.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportConverter.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportCsvConverter.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportType.java
mod-erm-usage-counter51/src/main/java/org/olf/erm/usage/counter51/ReportValidator.java
mod-erm-usage-counter51/src/test/java/org/olf/erm/usage/counter51/ReportTypeTest.java
mod-erm-usage-counter51/src/test/java/org/olf/erm/usage/counter51/ReportValidatorTest.java
mod-erm-usage-counter51/src/test/java/org/olf/erm/usage/counter51/TestUtil.java
mod-erm-usage-counter51/src/test/resources/TR_r51_with_invalid_report_items.json

https://folio-org.atlassian.net/browse/MODEUSCNT-56
* Updates `ReportValidator` to validate entire reports
* Adds `validate` and `isMasterReport` utility methods

[MODEUSCNT-56] Enhance Counter 5.1 Report Validation

---

Jenkinsfile
mod-erm-usage-counter-common/pom.xml
mod-erm-usage-counter41/pom.xml
mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter51/pom.xml
pom.xml

https://folio-org.atlassian.net/browse/MODEUSCNT-59
* Upgrades to Java 21
* Update other dependencies
* Bump major version

[MODEUSCNT-59] Upgrade to Java 21

---

NEWS.md
mod-erm-usage-counter-common/pom.xml
mod-erm-usage-counter41/pom.xml
mod-erm-usage-counter50/pom.xml
mod-erm-usage-counter51/pom.xml
pom.xml

https://folio-org.atlassian.net/browse/MODEUSCNT-60
* Release v5.0.0

[MODEUSCNT-60] Release v5.0.0

---

pom.xml

https://folio-org.atlassian.net/browse/MODEUS-209
CVE-2025-48734:
* https://lists.apache.org/thread/s0hb3jkfj5f3ryx6c57zqtfohb0of1g9
* https://github.com/advisories/GHSA-wxr5-93ph-8wr9

MODEUS-209: Upgrade commons-beanutils from 1.10.1 to 1.11.0 fixing CVE
